# Site settings
title: Kristina's Blog
email: kristina.frey.frey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  From coffee, to customer support, to software development, to parenting.
  I have expertise in many things people blog about, and so get ready.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kristinabrown.github.io/" # the base hostname & protocol for your site
twitter_username: kf_brown
github_username:  kristinabrown

# Build settings
markdown: kramdown

defaults:
  #set layout
  scope:
    path: "" # an empty string here means all files in the project
    type: "posts"
  values:
    layout: "default"
    author: "Kristina Brown"
